### PR TITLE
Remove hints about unavailable bluetooth

### PR DESCRIPTION
**Pull request by opatut**

### CODE REVIEW

**Review by gluap — APPROVED** [review]
Looks good to me, checked the new text and the whitespace changes look sensible.

**Review by gluap — APPROVED** [review]
Found the "viewed changes button" and approving again after using it.

**Review by amandel — APPROVED** [review]
👍

**Comment by opatut** [comment]
Oh yeah the whitespace is done automatically by my editor. We should introduce a `.editorconfig` so everybody's editor does that.

**Pull request merged**
